### ISSUE TITLE
Global symbols - crash when loading LADSPA plugins

### ISSUE THREAD

**Issue by x42** [grejppi/bitrot#1]
The plugins export all their symbols (see http://paste.debian.net/1005001/ )  e.g. `DISTRHO::Plugin::Plugin` in available the global namespace for each plugin.  When loading multiple plugins into the same address-space those symbols will conflict and produce crashes.

At the very least add `-fvisibility=hidden` to CXXFLAGS which solves this issue or alternatively place each plugin into its own unique C++ namespace.

Please consider using the DPF build system or rather the compiler flags, which would be (on Linux for gcc):
```
 CXXFLAGS="-fvisibility=hidden -fdata-sections -ffunction-sections" \
 LDFLAGS="-fvisibility=hidden -fdata-sections -ffunction-sections -Wl,--gc-sections -Wl,-O1 -Wl,--as-needed -Wl,--strip-all" \
 ./waf configure
```

**Comment by falkTX** [comment]
You can define `DISTRHO_NAMESPACE` and `DGL_NAMESPACE` to avoid symbol conflicts with other plugins.
Though if you hide symbols by default this is not an issue anyway.
Only really relevant for macOS right now.

**Comment by falkTX** [comment]
Oh, I also recommend having some optimization flags there.
At least `-O2`, or maybe `-O3 -mtune=generic`.
See https://github.com/DISTRHO/DPF-Plugins/blob/master/Makefile.mk#L26 for the usual dpf options.

**Comment by grejppi** [comment]
Which hosts does this happen in? Please check if 0e8d6a96ccc163d1b10ec1e0cc2e26c6f5bf3f3f resolves it 😊

**Comment by x42** [comment]
It came up on #ardour (IRC).

**Comment by x42** [comment]
And yes 0e8d6a96ccc163d1b10ec1e0cc2e26c6f5bf3f3f  fixes the crashes. Thanks!

PS. it would still be prudent to strip the binaries and heed suggestions from @falkTX above.
