### ISSUE TITLE
DPF submodule not found

### ISSUE THREAD

**Issue by JRSV** [grejppi/bitrot#7]
greetings

Cannot compile in UbuntuStudio 20.04 as `./waf configure` returns `DPF submodule not found!
Please run the following commands and try again:
  git submodule init
  git submodule update
`
I found [this](https://github.com/michaelwillis/dragonfly-reverb/issues/28) refering to a similar problem but I do not know if its relevant here.

best

**Comment by grejppi** [comment]
Have you tried running the suggested commands?

**Comment by JRSV** [comment]
those commands are for git. if I run them where downloaded it does nothing. As I understand in the link I sent you its a packaging issue of some sort in github

**Comment by grejppi** [comment]
Yeah, it is an unfortunate side effect of using git submodules, so if you want to build from source, you will need to clone the repository with git first.

I'm closing this because, as you said, it's an issue on GitHub's side.
